adjust

diff --git a/os/build/done/init.d/php-fpm b/os/build/done/init.d/php-fpm
--- a/os/build/done/init.d/php-fpm
+++ b/os/build/done/init.d/php-fpm
@@ -1,152 +1,111 @@
 #! /bin/sh
-
+#
+# chkconfig: - 84 16
+# description:	PHP FastCGI Process Manager
+# processname: php-fpm
+# config: /etc/php-fpm.conf
+# config: /etc/sysconfig/php-fpm
+# pidfile: /var/run/php-fpm/php-fpm.pid
+#
 ### BEGIN INIT INFO
-# Provides:          php-fpm
-# Required-Start:    $remote_fs $network
-# Required-Stop:     $remote_fs $network
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: starts php-fpm
-# Description:       starts the PHP FastCGI Process Manager daemon
+# Provides: php-fpm
+# Required-Start: $local_fs $remote_fs $network $named
+# Required-Stop: $local_fs $remote_fs $network
+# Short-Description: start and stop PHP FPM
+# Description: PHP FastCGI Process Manager
 ### END INIT INFO
 
-prefix=/usr
-exec_prefix=/usr
+# Standard LSB functions
+#. /lib/lsb/init-functions
 
-php_fpm_BIN=${exec_prefix}/sbin/php-fpm
-php_fpm_CONF=${prefix}/etc/php-fpm.conf
-php_fpm_PID=${prefix}/var/run/php-fpm.pid
+# Source function library.
+. /etc/init.d/functions
 
+# Check that networking is up.
+. /etc/sysconfig/network
 
-php_opts="--fpm-config $php_fpm_CONF --pid $php_fpm_PID"
+# Additional environment file
+if [ -f /etc/sysconfig/php-fpm ]; then
+      . /etc/sysconfig/php-fpm
+fi
 
+if [ "$NETWORKING" = "no" ]
+then
+	exit 0
+fi
 
-wait_for_pid () {
-	try=0
+RETVAL=0
+prog="php-fpm"
+pidfile=${PIDFILE-/var/run/php-fpm/php-fpm.pid}
+lockfile=${LOCKFILE-/var/lock/subsys/php-fpm}
 
-	while test $try -lt 35 ; do
-
-		case "$1" in
-			'created')
-			if [ -f "$2" ] ; then
-				try=''
-				break
-			fi
-			;;
-
-			'removed')
-			if [ ! -f "$2" ] ; then
-				try=''
-				break
-			fi
-			;;
-		esac
-
-		echo -n .
-		try=`expr $try + 1`
-		sleep 1
-
-	done
-
+start () {
+	echo -n $"Starting $prog: "
+	dir=$(dirname ${pidfile})
+	[ -d $dir ] || mkdir $dir
+	daemon --pidfile ${pidfile} /usr/sbin/php-fpm --daemonize
+	RETVAL=$?
+	echo
+	[ $RETVAL -eq 0 ] && touch ${lockfile}
+}
+stop () {
+	echo -n $"Stopping $prog: "
+	killproc -p ${pidfile} php-fpm
+	RETVAL=$?
+	echo
+	if [ $RETVAL -eq 0 ] ; then
+		rm -f ${lockfile} ${pidfile}
+	fi
 }
 
+restart () {
+        stop
+        start
+}
+
+reload () {
+	echo -n $"Reloading $prog: "
+	if ! /usr/sbin/php-fpm --test ; then
+	        RETVAL=6
+	        echo $"not reloading due to configuration syntax error"
+	        failure $"not reloading $prog due to configuration syntax error"
+	else
+		killproc -p ${pidfile} php-fpm -USR2
+		RETVAL=$?
+	fi
+	echo
+}
+
+
+# See how we were called.
 case "$1" in
-	start)
-		echo -n "Starting php-fpm "
-
-		$php_fpm_BIN --daemonize $php_opts
-
-		if [ "$?" != 0 ] ; then
-			echo " failed"
-			exit 1
-		fi
-
-		wait_for_pid created $php_fpm_PID
-
-		if [ -n "$try" ] ; then
-			echo " failed"
-			exit 1
-		else
-			echo " done"
-		fi
+  start)
+	start
 	;;
-
-	stop)
-		echo -n "Gracefully shutting down php-fpm "
-
-		if [ ! -r $php_fpm_PID ] ; then
-			echo "warning, no pid file found - php-fpm is not running ?"
-			exit 1
-		fi
-
-		kill -QUIT `cat $php_fpm_PID`
-
-		wait_for_pid removed $php_fpm_PID
-
-		if [ -n "$try" ] ; then
-			echo " failed. Use force-quit"
-			exit 1
-		else
-			echo " done"
-		fi
+  stop)
+	stop
 	;;
-
-	status)
-		if [ ! -r $php_fpm_PID ] ; then
-			echo "php-fpm is stopped"
-			exit 0
-		fi
-
-		PID=`cat $php_fpm_PID`
-		if ps -p $PID | grep -q $PID; then
-			echo "php-fpm (pid $PID) is running..."
-		else
-			echo "php-fpm dead but pid file exists"
-		fi
+  status)
+	status -p ${pidfile} php-fpm
+	RETVAL=$?
 	;;
-
-	force-quit)
-		echo -n "Terminating php-fpm "
-
-		if [ ! -r $php_fpm_PID ] ; then
-			echo "warning, no pid file found - php-fpm is not running ?"
-			exit 1
-		fi
-
-		kill -TERM `cat $php_fpm_PID`
-
-		wait_for_pid removed $php_fpm_PID
-
-		if [ -n "$try" ] ; then
-			echo " failed"
-			exit 1
-		else
-			echo " done"
-		fi
+  restart)
+	restart
 	;;
-
-	restart)
-		$0 stop
-		$0 start
+  reload|force-reload)
+	reload
 	;;
-
-	reload)
-
-		echo -n "Reload service php-fpm "
-
-		if [ ! -r $php_fpm_PID ] ; then
-			echo "warning, no pid file found - php-fpm is not running ?"
-			exit 1
-		fi
-
-		kill -USR2 `cat $php_fpm_PID`
-
-		echo " done"
+  configtest)
+ 	/usr/sbin/php-fpm --test
+	RETVAL=$?
 	;;
-
-	*)
-		echo "Usage: $0 {start|stop|force-quit|restart|reload|status}"
-		exit 1
+  condrestart|try-restart)
+	[ -f ${lockfile} ] && restart || :
 	;;
-
+  *)
+	echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|try-restart|configtest}"
+	RETVAL=2
+        ;;
 esac
+
+exit $RETVAL
