整理

diff --git a/os/centos/6/init.d/nginx b/os/centos/6/init.d/nginx
--- a/os/centos/6/init.d/nginx
+++ b/os/centos/6/init.d/nginx
@@ -21,16 +21,25 @@
 # Source function library.
 . /etc/rc.d/init.d/functions
 
-if [ -f /etc/sysconfig/nginx ]; then
-    . /etc/sysconfig/nginx
+if [ -L $0 ]; then
+    initscript=`/bin/readlink -f $0`
+else
+    initscript=$0
 fi
 
-prog=nginx
+sysconfig=`/bin/basename $initscript`
+
+if [ -f /etc/sysconfig/$sysconfig ]; then
+    . /etc/sysconfig/$sysconfig
+fi
+
 nginx=${NGINX-/usr/sbin/nginx}
+prog=`/bin/basename $nginx`
 conffile=${CONFFILE-/etc/nginx/nginx.conf}
 lockfile=${LOCKFILE-/var/lock/subsys/nginx}
 pidfile=${PIDFILE-/var/run/nginx.pid}
-SLEEPMSEC=100000
+SLEEPMSEC=${SLEEPMSEC-200000}
+UPGRADEWAITLOOPS=${UPGRADEWAITLOOPS-5}
 RETVAL=0
 
 start() {
@@ -61,21 +70,24 @@ reload() {
 upgrade() {
     oldbinpidfile=${pidfile}.oldbin
 
-    configtest -q || return 6
-    echo -n $"Staring new master $prog: "
+    configtest -q || return
+    echo -n $"Starting new master $prog: "
     killproc -p ${pidfile} ${prog} -USR2
-    RETVAL=$?
     echo
-    /bin/usleep $SLEEPMSEC
-    if [ -f ${oldbinpidfile} -a -f ${pidfile} ]; then
-        echo -n $"Graceful shutdown of old $prog: "
-        killproc -p ${oldbinpidfile} ${prog} -QUIT
-        RETVAL=$?
-        echo 
-    else
-        echo $"Upgrade failed!"
-        return 1
-    fi
+
+    for i in `/usr/bin/seq $UPGRADEWAITLOOPS`; do
+        /bin/usleep $SLEEPMSEC
+        if [ -f ${oldbinpidfile} -a -f ${pidfile} ]; then
+            echo -n $"Graceful shutdown of old $prog: "
+            killproc -p ${oldbinpidfile} ${prog} -QUIT
+            RETVAL=$?
+            echo
+            return
+        fi
+    done
+
+    echo $"Upgrade failed!"
+    RETVAL=1
 }
 
 configtest() {
@@ -117,6 +129,7 @@ case "$1" in
         start
         ;;
     upgrade)
+        rh_status >/dev/null 2>&1 || exit 0
         upgrade
         ;;
     condrestart|try-restart)
